/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 */

#include <lcm/lcm_coretypes.h>

#ifndef __nav_enable_t_hpp__
#define __nav_enable_t_hpp__

class nav_enable_t
{
    public:
        int32_t    enable;   // 导航使能标志：1=开启导航, 0=关闭导航

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int nav_enable_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int nav_enable_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int nav_enable_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t nav_enable_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* nav_enable_t::getTypeName()
{
    return "nav_enable_t";
}

int nav_enable_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->enable, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int nav_enable_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->enable, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int nav_enable_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t nav_enable_t::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0xae72f3b1c84d05e9LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
